# .github/workflows/version-bump.yml
name: Auto Version Bump

on:
  pull_request:
    types: [closed]
    branches:
      - '*'  # This will trigger on PRs to any branch

jobs:
  version-bump:
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes
      pull-requests: read  # Needed for PR information

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
          fetch-depth: 0  # Fetch all history for git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Update Version
        run: |
          # Read current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Increment patch version
          NEW_VERSION=$(node -p "
            const [major, minor, patch] = '$CURRENT_VERSION'.split('.');
            `${major}.${minor}.${Number(patch) + 1}`
          ")

          # Update package.json with new version
          node -e "
            const fs = require('fs');
            const package = require('./package.json');
            package.version = '$NEW_VERSION';
            fs.writeFileSync('package.json', JSON.stringify(package, null, 2) + '\n');
          "

          # Create and push changes
          git add package.json
          git commit -m "chore: bump version to ${NEW_VERSION} [skip ci]"
          git push origin ${GITHUB_REF#refs/heads/}