name: "Auto version patch on merge"

on:
  pull_request_target:
    branches:
      - "main"
      - "dxkb.theseed"
      - "dev"
      - "test"
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write

jobs:
  bump-version:
    if: github.event.pull_request.merged
    name: "Patch version on specified branches upon merge"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 20
      - name: "run 'npm version patch'"
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          npm version patch
      - name: "cat package.json"
        run: cat ./package.json